marketplace/config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  devise_for :users
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

marketplace/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
        can :read, :all
        can :manage, Item do |item|
            item.try(:user)== user#checking if the current user owns this item or not #so the do block here is checking to see if the current logged in user also owns this item or not
        end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

marketplace/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

marketplace/app/models/item.rb
class Item < ApplicationRecord

	belongs_to :user
	has_attached_file :image
	has_attached_file :resource
	#validates_attachment :image, presence: true,
	#content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
	#message: 'Only images allowed'
	#validates_attachment :resource, presence: true,
	#content_type: { content_type: ["image/jpeg", "image/gif", "image/png","application/pdf"] }

end

marketplace/app/models/sale.rb
class Sale < ApplicationRecord

	before_create :populate_uuid
	belongs_to :item

	private

	def populate_uuid
		self.uuid = SecureRandom.uuid() #generate random sequence number
end

marketplace/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

marketplace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, notice:"you are not authorize to access this page"
  end
  
end

marketplace/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.where(availability:true)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    authorize! :manage, @item #to implement cancan on edit function , so here we are authroizing the manage ability for the item
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize! :manage, @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize! :manage, @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :availability, :image, :resource)
    end
end

marketplace/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  
  	if current_user
  		redirect_to items_path
  	end
 end

 def dashboard
 	@items = current_user.items
 end

end

marketplace/app/helpers/application_helper.rb
module ApplicationHelper
end

marketplace/app/helpers/items_helper.rb
module ItemsHelper
end

marketplace/app/helpers/pages_helper.rb
module PagesHelper
end

marketplace/app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :resource %>
    <%= f.input :price %>
    <%= f.input :availability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

marketplace/app/views/items/_item.html.erb
<div class = 'col-md-3'
  <div class = 'thumbnail'>
    <%= image_tag 'cover.jpg', class: 'img-responsive'%>
  </div>
  <div class = 'caption'>
    <p><strong><%= link_to item.name, item_path(item) %></strong></p>
              <p>$<%= item.price/100 %></p>
  </div>
</div>

marketplace/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

marketplace/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<div class ="row">

<%= render @items %>

<br>

</div>

<%= link_to 'New Item', new_item_path %>

marketplace/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

marketplace/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6"><%= image_tag "cover.jpeg", class: 'img-responsive'%>
  	
  </div>
  <div class="col-md-6">



<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @item.price/100 %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @item.availability %>
</p>
</div>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

marketplace/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-1" aria-expanded="true" style="">
      <ul class="nav navbar-nav">
        
        
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'Log Out' ,destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Profile' ,edit_user_registration_path %></li>
          <li><%= link_to 'Dashboard' ,dashboard_path %></li>
          <li><%= link_to 'Marketplace' ,root_path %></li>
        
        <%else%>

          <li><%= link_to 'Log in' , new_user_session_path %></li>
        <%end%>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

marketplace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render 'layouts/navbar'%>
  	<div class = 'container'>
    	<%= yield %>
    </div>

  </body>
</html>

marketplace/app/views/pages/dashboard.html.erb
<h1> Dashboard </h1>

<div class = "row">
<div class = 'col-md-4'>
<h3>Items</h3>
<table class="table table-condensed"> 
<thead> <tr> 
<th>#</th> 
<th>ID</th> 
<th>Item Name</th> 
<th>Available</th> 
</tr> 
</thead> 
<tbody> 
<% @items.each do |item| %>
<tr> 
<td><%= item.id %></td> 
<td><%= item.name %></td> 
<td><%= item.availability %></td> 
</tr> 
<%end%>
</tbody> 
</table>
</div>
<div class = 'col-md-4'>
<h3>Purchases</h3>
</div>
<div class = 'col-md-4'>
<h3>Sales</h3>
</div>
</div>

marketplace/app/views/pages/home.html.erb
<div class = 'jumbotron'>

<h1> Welcome to onlinecart Website </h1>
<%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
<%= link_to 'Items', items_path, class: 'btn btn-primary btn-lg' %>

</div>